[versions]
gson = "2.14.0"
assertj = "3.27.7"
logback = "1.5.38"
okhttp = "5.4.0"
testng = "7.12.0"

[libraries]
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
logback-core = { module = "ch.qos.logback:logback-core", version.ref = "logback" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
mockwebserver3 = { module = "com.squareup.okhttp3:mockwebserver3", version.ref = "okhttp" }
testng = { module = "org.testng:testng", version.ref = "testng" }
