apply plugin: 'maven-publish'
apply plugin: 'signing'

nexusPublishing {
    repositories {
        sonatype {
            nexusUrl.set(uri("https://ossrh-staging-api.central.sonatype.com/service/local/"))
            snapshotRepositoryUrl.set(uri("https://central.sonatype.com/repository/maven-snapshots/"))
            username.set(providers.gradleProperty("sonatypeUsername"))
            password.set(providers.gradleProperty("sonatypePassword"))
        }
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifact sourcesJar
            artifact testsJar
            artifact docsJar

            pom.withXml {
                def root = asNode()
                root.appendNode('name', 'Jenkins Rest')
                root.appendNode('description', 'Java client for working with Jenkins REST API.')
                root.appendNode('url', 'https://github.com/pdasilem/jenkins-rest')
                root.appendNode('inceptionYear', '2016')

                def scm = root.appendNode('scm')
                scm.appendNode('url', 'https://github.com/pdasilem/jenkins-rest')
                scm.appendNode('connection', 'scm:https://pdasilem@github.com/pdasilem/jenkins-rest.git')
                scm.appendNode('developerConnection', 'scm:git://github.com/pdasilem/jenkins-rest.git')

                def license = root.appendNode('licenses').appendNode('license')
                license.appendNode('name', 'The Apache Software License, Version 2.0')
                license.appendNode('url', 'http://www.apache.org/licenses/LICENSE-2.0.txt')
                license.appendNode('distribution', 'repo')

                def developers = root.appendNode('developers')
                def pdasilem = developers.appendNode('developer')
                pdasilem.appendNode('id', 'pdasilem')
                pdasilem.appendNode('name', 'Sergei M')
                pdasilem.appendNode('email', 'pdasilem@gmail.com')
            }
        }
    }
}

signing {
    sign publishing.publications.mavenJava
}
