buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'org.eclipse.jgit:org.eclipse.jgit:7.7.0.202606012155-r'
    }
}

import org.eclipse.jgit.api.Git
import org.eclipse.jgit.api.DeleteTagCommand
import org.eclipse.jgit.api.TagCommand
import org.eclipse.jgit.api.PushCommand
import org.eclipse.jgit.storage.file.FileRepositoryBuilder
import org.eclipse.jgit.transport.UsernamePasswordCredentialsProvider

def openGit = {
    new Git(new FileRepositoryBuilder().findGitDir(project.projectDir).build())
}

tasks.register('createTag') {
    description = 'Creates repository tag with current project version.'
    ext.tagName = "v${project.version}"

    doLast {
        logger.quiet "Creating tag '$tagName'."
        def git = openGit()

        // Remove potentially existing tag
        DeleteTagCommand delTag = git.tagDelete()
        delTag.setTags(tagName).call()

        // Create tag
        TagCommand tag = git.tag()
        tag.setName(tagName).setMessage("Version ${project.version}").call()
    }
}

tasks.register('pushTag') {
    description = 'Pushes tag to remote repository.'
    dependsOn tasks.named('createTag')

    doLast {
        def tagName = tasks.named('createTag').get().tagName
        logger.quiet "Pushing tag '$tagName' to remote."
        def git = openGit()

        PushCommand push = git.push()
        push.add(tagName)
        push.setCredentialsProvider(new UsernamePasswordCredentialsProvider(project.githubUsername, project.githubPassword))
        push.call()
    }
}

tasks.register('tag') {
    dependsOn tasks.named('pushTag')
    mustRunAfter "publishToSonatype", "closeAndReleaseSonatypeStagingRepository"
}

tasks.register('release') {
    description = 'Publishes artifacts to Maven Central and tags repository with current project version.'
    dependsOn tasks.named('assemble'), "publishToSonatype", "closeAndReleaseSonatypeStagingRepository", tasks.named('tag')
}
